TABLE_DEFINITIONS = {
    "Самое важное": [
        {"name": "address", "type": "text"},
        {"name": "price", "type": "number"},
        {"name": "notes", "type": "long_text"},
        {"name": "owner_phone", "type": "text"},
        {"name": "created_at", "type": "date"},
        {"name": "locked_by", "type": "number"},
        {"name": "locked_until", "type": "date"},
    ],
    "Показы, действия": [
        {"name": "address", "type": "text"},
        {"name": "datetime", "type": "date"},
        {"name": "client_name", "type": "text"},
        {"name": "client_phone", "type": "text"},
        {"name": "status", "type": "single_select"},
        {"name": "notes", "type": "long_text"},
        {"name": "executor", "type": "number"},
    ],
    "Успешные Сделки": [
        {"name": "address", "type": "text"},
        {"name": "commission_amount", "type": "number"},
        {"name": "commission_percent", "type": "number"},
        {"name": "agent_id", "type": "number"},
        {"name": "date", "type": "date"},
        {"name": "related_task", "type": "text"},
    ],
    "Типаж Рабочий Чат": [
        {"name": "link", "type": "text"},
        {"name": "notes", "type": "long_text"},
    ],
    "Авито": [
        {"name": "address", "type": "text"},
        {"name": "avito_link", "type": "text"},
        {"name": "owner_phone", "type": "text"},
        {"name": "status", "type": "single_select"},
    ],
    "Недозвон": [
        {"name": "address", "type": "text"},
        {"name": "owner_phone", "type": "text"},
        {"name": "last_attempt", "type": "date"},
        {"name": "notes", "type": "long_text"},
    ],
    "Неликвид": [
        {"name": "address", "type": "text"},
        {"name": "reason", "type": "long_text"},
        {"name": "price", "type": "number"},
    ],
    "Актуальные клиенты": [
        {"name": "client_name", "type": "text"},
        {"name": "phone", "type": "text"},
        {"name": "requirements", "type": "long_text"},
        {"name": "budget", "type": "number"},
    ],
    "Будут сдавать": [
        {"name": "address", "type": "text"},
        {"name": "expected_free_date", "type": "date"},
        {"name": "owner_phone", "type": "text"},
    ],
    "Не работают": [
        {"name": "address", "type": "text"},
        {"name": "owner_phone", "type": "text"},
        {"name": "notes", "type": "long_text"},
    ],
    "Собрание, рабочие процессы": [
        {"name": "title", "type": "text"},
        {"name": "notes", "type": "long_text"},
        {"name": "date", "type": "date"},
    ],
    "Открытые источники": [
        {"name": "address", "type": "text"},
        {"name": "source_link", "type": "text"},
        {"name": "owner_phone", "type": "text"},
    ],
    "Под вопросом": [
        {"name": "address", "type": "text"},
        {"name": "notes", "type": "long_text"},
    ],
    "Общак": [
        {"name": "amount", "type": "number"},
        {"name": "type", "type": "single_select"},
        {"name": "reason", "type": "long_text"},
        {"name": "date", "type": "date"},
        {"name": "from_agent", "type": "number"},
    ],
    "Срочные клиенты": [
        {"name": "client_name", "type": "text"},
        {"name": "phone", "type": "text"},
        {"name": "requirements", "type": "long_text"},
        {"name": "urgency", "type": "single_select"},
    ],
    "Будут покупать": [
        {"name": "client_name", "type": "text"},
        {"name": "budget", "type": "number"},
        {"name": "notes", "type": "long_text"},
    ],
    "Чат болталка": [
        {"name": "link", "type": "text"},
        {"name": "notes", "type": "long_text"},
    ],
    "Будут продавать": [
        {"name": "address", "type": "text"},
        {"name": "owner_phone", "type": "text"},
        {"name": "notes", "type": "long_text"},
    ],
    "Задачи": [
        {"name": "title", "type": "text"},
        {"name": "details", "type": "long_text"},
        {"name": "assigned_to", "type": "number"},
        {"name": "created_by", "type": "number"},
        {"name": "status", "type": "single_select"},
        {"name": "due_date", "type": "date"},
    ],
    "Объекты": [
        {"name": "title", "type": "text"},
        {"name": "address", "type": "text"},
        {"name": "price", "type": "number"},
        {"name": "district", "type": "text"},
        {"name": "photos", "type": "file"},
        {"name": "owner_phone", "type": "text"},
        {"name": "status", "type": "single_select"},
        {"name": "assigned_to", "type": "number"},
    ],
}
